### ISSUE TITLE
Webpage show nothing but Compact, hide players and "loading..."

### ISSUE THREAD

**Issue by sdosker** [Dantevg/WebStats#81] opened 2023-09-26 14:22 UTC
After setting it up, it only shows up those info on the webpage, no players, no stats.

The console shows up this warning:
`[11:26:24 WARN]: [WebStats] Could not find resource web/WebStats-dist.js`

But, messing with the WebStats-dist.js and index.html made the server crash with a spam of the following error:

```
[11:15:06 ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH  - git-Purpur-2062 (MC: 1.20.1) ---
[11:15:06 ERROR]: The server has not responded for 10 seconds! Creating thread dump
[11:15:06 ERROR]: ------------------------------
[11:15:06 ERROR]: Server thread dump (Look for plugins here before reporting to Purpur!):
[11:15:06 ERROR]: ------------------------------
[11:15:06 ERROR]: Current Thread: Server thread
[11:15:06 ERROR]: 	PID: 29 | Suspended: false | Native: false | State: RUNNABLE
[11:15:06 ERROR]: 	Stack:
[11:15:06 ERROR]: 		java.base@17.0.7/java.util.HashMap.keysToArray(HashMap.java:949)
[11:15:06 ERROR]: 		java.base@17.0.7/java.util.HashMap$KeySet.toArray(HashMap.java:993)
[11:15:06 ERROR]: 		java.base@17.0.7/java.util.ArrayList.<init>(ArrayList.java:181)
[11:15:06 ERROR]: 		com.google.common.collect.Lists.newArrayList(Lists.java:131)
[11:15:06 ERROR]: 		net.minecraft.world.scores.Scoreboard.getTrackedPlayers(Scoreboard.java:115)
[11:15:06 ERROR]: 		org.bukkit.craftbukkit.v1_20_R1.scoreboard.CraftScore.isScoreSet(CraftScore.java:64)
[11:15:06 ERROR]: 		WebStats-1.9.1+mc1.18+.jar//nl.dantevg.webstats.scoreboard.ScoreboardSource.getScores(ScoreboardSource.java:44)
[11:15:06 ERROR]: 		WebStats-1.9.1+mc1.18+.jar//nl.dantevg.webstats.scoreboard.ScoreboardSource.getStats(ScoreboardSource.java:54)
[11:15:06 ERROR]: 		WebStats-1.9.1+mc1.18+.jar//nl.dantevg.webstats.Stats.getStats(Stats.java:25)
[11:15:06 ERROR]: 		WebStats-1.9.1+mc1.18+.jar//nl.dantevg.webstats.StatExporter.export(StatExporter.java:47)
[11:15:06 ERROR]: 		WebStats-1.9.1+mc1.18+.jar//nl.dantevg.webstats.CommandWebstats.onCommand(CommandWebstats.java:33)
[11:15:06 ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:15:06 ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[11:15:06 ERROR]: 		org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001)
[11:15:06 ERROR]: 		org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:986)
[11:15:06 ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:540)
[11:15:06 ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487)
[11:15:06 ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420)
[11:15:06 ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191)
[11:15:06 ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[11:15:06 ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$4772/0x0000000801a43038.run(Unknown Source)
[11:15:06 ERROR]: 		java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
[11:15:06 ERROR]: ------------------------------
[11:15:06 ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH ---
[11:15:06 ERROR]: ------------------------------
```

I'm also using the Vannila tweaks datapack (track raw statistics v1.7.1 (MC 1.20-1.20.2))

Also impossibe to get the "/stats.json" or use the /webstats export command (the command also halts the server)

**Comment by Dantevg** [comment] 2023-09-26 15:32
Thanks for the report! It appears I have messed up compiling the plugin and forgot to include the js file 🤦‍♂️, that's fixed now for all downloads.

The server crashing on `/webstats export` or loading `/stats.json` is really weird, though. Could you post your `config.yml` here? What server version are you running?

PS. I formatted your log, hope you don't mind.

**Comment by sdosker** [comment] 2023-09-26 15:45
I've updated with the new file, now it doesn't report errors on the console, but stills seems to halt the runtime.

and the command `/webstats export` doesn't seem to do anything

Here's the config https://pastebin.com/48e63Xv4 (no changes at all i think...)

And a screenshot of the web view:
![captura](https://github.com/Dantevg/WebStats/assets/6579456/1c055854-87ee-4911-8075-8ccdb73a9d50)

**Comment by Dantevg** [comment] 2023-09-26 16:05
I'm sad to say that I cannot reproduce this, with a clean purpur build 2062 server, track raw stats and WebStats with your exact config. Maybe you have some other plugin causing this?

**Comment by sdosker** [comment] 2023-09-26 16:29
Good to know, in the next days I'll clone the server files and remove things one by one until i find out what's causing this

**Comment by sdosker** [comment] 2023-09-26 17:38
Update: 
Found out it wasn't any other plugins, but something in my "world" folder (i've deleted it and the problem disappeared)
Still moving and deleting things trying to find out the exatly reason.

**Comment by Dantevg** [comment] 2023-09-26 17:41
Glad you managed to find the issue! Closing this now, I assume it's all working fine.

**Closed by Dantevg** 2023-09-26 17:41 UTC
Labels: bug

**Comment by Dantevg** [comment] 2023-09-27 10:04
> [...]
> Edit: the problem was the `world/data/scoreboard.dat` file, not sure the reason anyway... (maybe too big? 346kb) Deleted and now it is working

That is certainly larger than my scoreboard file, which is 17kB (for about 10 players). Maybe some plugin is misusing the scoreboard, if it happens again you might be able to find it by opening `scoreboard.dat` with NBTExplorer.
